version: '3.9'

volumes:
  db:

services:
  mongodb:
    container_name: mongodb-oc
    image: mongo:7.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
